"""Authoritative Master Grocery Catalog - Dairy, Eggs & Bakery."""

DAIRY_MASTER_CATALOG = [
    {
        "sku": "PROD-AMUL-BUTTER-500G",
        "name": "Amul Pasteurised Salted Butter 500g",
        "slug": "amul-butter-500g",
        "brand": "Amul",
        "base_price": 285.0,
        "sale_price": 275.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0405",
        "shelf_life_days": 180,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 717,
            "carbohydrates_g": 0.0,
            "protein_g": 0.5,
            "fat_g": 80.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AMUL-BUTTER-100G",
        "name": "Amul Pasteurised Salted Butter 100g",
        "slug": "amul-butter-100g",
        "brand": "Amul",
        "base_price": 60.0,
        "sale_price": 58.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0405",
        "shelf_life_days": 180,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 717,
            "carbohydrates_g": 0.0,
            "protein_g": 0.5,
            "fat_g": 80.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-MOTHER-DAIRY-BUTTER-500G",
        "name": "Mother Dairy Pure Table Butter 500g",
        "slug": "mother-dairy-butter-500g",
        "brand": "Mother Dairy",
        "base_price": 280.0,
        "sale_price": 270.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0405",
        "shelf_life_days": 180,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 715,
            "carbohydrates_g": 0.0,
            "protein_g": 0.6,
            "fat_g": 79.5,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-MOTHER-DAIRY-BUTTER-100G",
        "name": "Mother Dairy Pure Table Butter 100g",
        "slug": "mother-dairy-butter-100g",
        "brand": "Mother Dairy",
        "base_price": 58.0,
        "sale_price": 56.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0405",
        "shelf_life_days": 180,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 715,
            "carbohydrates_g": 0.0,
            "protein_g": 0.6,
            "fat_g": 79.5,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AMUL-TAAZA-TONED-MILK-1L",
        "name": "Amul Taaza Homogenised Toned Milk 1L",
        "slug": "amul-taaza-toned-milk-1l",
        "brand": "Amul",
        "base_price": 75.0,
        "sale_price": 72.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 180,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 58,
            "carbohydrates_g": 4.7,
            "protein_g": 3.0,
            "fat_g": 3.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AMUL-GOLD-FULL-CREAM-1L",
        "name": "Amul Gold Pasteurised Full Cream Milk 1L",
        "slug": "amul-gold-full-cream-1l",
        "brand": "Amul",
        "base_price": 86.0,
        "sale_price": 82.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 180,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 87,
            "carbohydrates_g": 5.0,
            "protein_g": 3.2,
            "fat_g": 6.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AMUL-COW-MILK-1L",
        "name": "Amul Cow Milk 1L",
        "slug": "amul-cow-milk-1l",
        "brand": "Amul",
        "base_price": 78.0,
        "sale_price": 74.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 180,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 62,
            "carbohydrates_g": 4.8,
            "protein_g": 3.1,
            "fat_g": 3.5,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-NANDINI-GOODLIFE-TONED-1L",
        "name": "Nandini GoodLife Pure Toned Milk 1L",
        "slug": "nandini-goodlife-toned-1l",
        "brand": "Nandini",
        "base_price": 72.0,
        "sale_price": 68.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 180,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 57,
            "carbohydrates_g": 4.6,
            "protein_g": 3.0,
            "fat_g": 3.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-NANDINI-GOODLIFE-COW-1L",
        "name": "Nandini GoodLife Cow Milk 1L",
        "slug": "nandini-goodlife-cow-1l",
        "brand": "Nandini",
        "base_price": 74.0,
        "sale_price": 70.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 180,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 60,
            "carbohydrates_g": 4.7,
            "protein_g": 3.1,
            "fat_g": 3.5,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-COUNTRY-DELIGHT-DESI-COW-MILK-1L",
        "name": "Country Delight Farm Fresh Desi Cow Milk 1L",
        "slug": "country-delight-desi-cow-milk-1l",
        "brand": "Country Delight",
        "base_price": 90.0,
        "sale_price": 85.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 3,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 65,
            "carbohydrates_g": 4.9,
            "protein_g": 3.3,
            "fat_g": 4.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-COUNTRY-DELIGHT-BUFFALO-MILK-1L",
        "name": "Country Delight Buffalo Milk 1L",
        "slug": "country-delight-buffalo-milk-1l",
        "brand": "Country Delight",
        "base_price": 100.0,
        "sale_price": 95.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0401",
        "shelf_life_days": 3,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 98,
            "carbohydrates_g": 5.2,
            "protein_g": 3.8,
            "fat_g": 7.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AKSHAYAKALPA-ORGANIC-PANEER-200G",
        "name": "Akshayakalpa Organic Artisan Paneer 200g",
        "slug": "akshayakalpa-organic-paneer-200g",
        "brand": "Akshayakalpa",
        "base_price": 165.0,
        "sale_price": 150.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0406",
        "shelf_life_days": 14,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 295,
            "carbohydrates_g": 2.5,
            "protein_g": 18.5,
            "fat_g": 23.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G",
        "name": "Amul Fresh Malai Paneer 200g",
        "slug": "amul-fresh-malai-paneer-200g",
        "brand": "Amul",
        "base_price": 98.0,
        "sale_price": 92.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0406",
        "shelf_life_days": 45,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 289,
            "carbohydrates_g": 2.0,
            "protein_g": 18.0,
            "fat_g": 23.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G",
        "name": "Mother Dairy Classic Dahi / Curd 400g",
        "slug": "mother-dairy-classic-dahi-400g",
        "brand": "Mother Dairy",
        "base_price": 45.0,
        "sale_price": 40.0,
        "unit": "tub",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0403",
        "shelf_life_days": 15,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 60,
            "carbohydrates_g": 4.4,
            "protein_g": 3.1,
            "fat_g": 3.1,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-EPIGAMIA-GREEK-YOGURT-NATURAL",
        "name": "Epigamia Greek Yogurt Natural 100g",
        "slug": "epigamia-greek-yogurt-natural",
        "brand": "Epigamia",
        "base_price": 50.0,
        "sale_price": 45.0,
        "unit": "cup",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0403",
        "shelf_life_days": 21,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 85,
            "carbohydrates_g": 3.5,
            "protein_g": 7.5,
            "fat_g": 4.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-HEALTH-FACTORY-ZERO-MAIDA-BREAD",
        "name": "The Health Factory Zero Maida Whole Wheat Bread 350g",
        "slug": "health-factory-zero-maida-bread",
        "brand": "The Health Factory",
        "base_price": 60.0,
        "sale_price": 55.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "1905",
        "shelf_life_days": 6,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 240,
            "carbohydrates_g": 45.0,
            "protein_g": 9.0,
            "fat_g": 2.5,
            "dietary_fiber_g": 7.0,
        },
    },
    {
        "sku": "PROD-EGGOZ-BROWN-EGGS-6PC",
        "name": "Eggoz Farm Fresh Brown Eggs 6-Pack",
        "slug": "eggoz-brown-eggs-6pc",
        "brand": "Eggoz",
        "base_price": 85.0,
        "sale_price": 78.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": "Organic" in name,
        "is_vegetarian": "Egg" not in name,
        "is_vegan": False,
        "hsn_code": "0407",
        "shelf_life_days": 21,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 143,
            "carbohydrates_g": 0.8,
            "protein_g": 12.6,
            "fat_g": 9.5,
            "dietary_fiber_g": 0.0,
        },
    },
]
