"""Authoritative Master Grocery Catalog - Dairy, Eggs & Bakery."""

DAIRY_CATALOG = [
    {
        "sku": "PROD-AMUL-BUTTER-500G",
        "name": "Amul Pasteurised Butter 500g",
        "slug": "amul-butter-500g",
        "brand": "Amul",
        "price": 275.0,
        "mrp": 285.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0405",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-MOTHER-DAIRY-BUTTER-500G",
        "name": "Mother Dairy Pure Table Butter 500g",
        "slug": "mother-dairy-butter-500g",
        "brand": "Mother Dairy",
        "price": 270.0,
        "mrp": 280.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0405",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-AMUL-TAAZA-MILK-1L",
        "name": "Amul Taaza Homogenised Toned Milk 1L",
        "slug": "amul-taaza-milk-1l",
        "brand": "Amul",
        "price": 72.0,
        "mrp": 75.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0401",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-NANDINI-GOODLIFE-1L",
        "name": "Nandini GoodLife Pure Cow Milk 1L",
        "slug": "nandini-goodlife-1l",
        "brand": "Nandini",
        "price": 68.0,
        "mrp": 72.0,
        "unit": "tetra",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0401",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-COUNTRY-DELIGHT-COW-MILK-1L",
        "name": "Country Delight Fresh Desi Cow Milk 1L",
        "slug": "country-delight-cow-milk-1l",
        "brand": "Country Delight",
        "price": 85.0,
        "mrp": 90.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0401",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-AKSHAYAKALPA-ORGANIC-PANEER-200G",
        "name": "Akshayakalpa Organic Artisan Paneer 200g",
        "slug": "akshayakalpa-organic-paneer-200g",
        "brand": "Akshayakalpa",
        "price": 150.0,
        "mrp": 165.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0406",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-AMUL-FRESH-PANEER-200G",
        "name": "Amul Fresh Malai Paneer 200g",
        "slug": "amul-fresh-paneer-200g",
        "brand": "Amul",
        "price": 92.0,
        "mrp": 98.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0406",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-MOTHER-DAIRY-DAHI-400G",
        "name": "Mother Dairy Classic Dahi / Curd 400g",
        "slug": "mother-dairy-dahi-400g",
        "brand": "Mother Dairy",
        "price": 40.0,
        "mrp": 45.0,
        "unit": "tub",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0403",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-MILKY-MIST-GREEK-YOGURT-100G",
        "name": "Milky Mist Greek Yogurt Natural 100g",
        "slug": "milky-mist-greek-yogurt-100g",
        "brand": "Milky Mist",
        "price": 45.0,
        "mrp": 50.0,
        "unit": "cup",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0403",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-EPIGAMIA-BLUEBERRY-YOGURT-120G",
        "name": "Epigamia Blueberry Greek Yogurt 120g",
        "slug": "epigamia-blueberry-yogurt-120g",
        "brand": "Epigamia",
        "price": 60.0,
        "mrp": 65.0,
        "unit": "cup",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0403",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-HEALTH-FACTORY-WHOLE-WHEAT-BREAD",
        "name": "The Health Factory Zero Maida Whole Wheat Bread 350g",
        "slug": "health-factory-whole-wheat-bread",
        "brand": "The Health Factory",
        "price": 55.0,
        "mrp": 60.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "1905",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-MODERN-WHOLE-WHEAT-BREAD-400G",
        "name": "Modern 100% Whole Wheat Bread 400g",
        "slug": "modern-whole-wheat-bread-400g",
        "brand": "Modern",
        "price": 45.0,
        "mrp": 50.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1905",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-ENGLISH-OVEN-MULTIGRAIN-BREAD",
        "name": "English Oven Multigrain Sliced Bread 400g",
        "slug": "english-oven-multigrain-bread",
        "brand": "English Oven",
        "price": 58.0,
        "mrp": 65.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1905",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-AMUL-CHEESE-CUBES-200G",
        "name": "Amul Processed Cheese Cubes 200g",
        "slug": "amul-cheese-cubes-200g",
        "brand": "Amul",
        "price": 135.0,
        "mrp": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0406",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-BRITANNIA-CHEESE-SLICES-200G",
        "name": "Britannia Cheese Slices 200g 10 Slices",
        "slug": "britannia-cheese-slices-200g",
        "brand": "Britannia",
        "price": 145.0,
        "mrp": 155.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0406",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-EGGOZ-BROWN-EGGS-6PC",
        "name": "Eggoz Farm Fresh Brown Eggs 6-Pack",
        "slug": "eggoz-brown-eggs-6pc",
        "brand": "Eggoz",
        "price": 78.0,
        "mrp": 85.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0407",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
    {
        "sku": "PROD-FRESHO-WHITE-EGGS-12PC",
        "name": "Fresho Farm White Eggs 12-Pack",
        "slug": "fresho-white-eggs-12pc",
        "brand": "Fresho",
        "price": 96.0,
        "mrp": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0407",
        "shelf_life_days": 15,
        "storage": "CHILLED",
    },
]
