"""Authoritative Master Grocery Catalog - Fresh Produce & Fruits."""

PRODUCE_CATALOG = [
    {
        "sku": "PROD-TOMATOES-HYBRID",
        "name": "Organic Hybrid Tomatoes",
        "slug": "tomatoes-hybrid",
        "brand": "FarmDirect",
        "price": 42.0,
        "mrp": 48.0,
        "unit": "kg",
        "is_variable_weight": True,
        "is_organic": True,
        "hsn_code": "0702",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-ONIONS-NASHIK",
        "name": "Nashik Red Onions",
        "slug": "onions-nashik",
        "brand": "FarmDirect",
        "price": 28.0,
        "mrp": 35.0,
        "unit": "kg",
        "is_variable_weight": True,
        "is_organic": False,
        "hsn_code": "0703",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-POTATOES-AGRA",
        "name": "Agra Golden Potatoes",
        "slug": "potatoes-agra",
        "brand": "FarmDirect",
        "price": 32.0,
        "mrp": 38.0,
        "unit": "kg",
        "is_variable_weight": True,
        "is_organic": False,
        "hsn_code": "0701",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-APPLES-ROYAL-GALA",
        "name": "Crisp Royal Gala Apples 4-Pack",
        "slug": "apples-royal-gala",
        "brand": "Himalayan Orchards",
        "price": 165.0,
        "mrp": 190.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0808",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-BANANAS-ROBUSTA",
        "name": "Robusta Golden Bananas 1kg",
        "slug": "bananas-robusta",
        "brand": "FarmDirect",
        "price": 45.0,
        "mrp": 52.0,
        "unit": "kg",
        "is_variable_weight": True,
        "is_organic": False,
        "hsn_code": "0803",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-CAPSICUM-GREEN",
        "name": "Fresh Green Capsicum / Bell Pepper 500g",
        "slug": "capsicum-green",
        "brand": "FarmDirect",
        "price": 35.0,
        "mrp": 42.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-SPINACH-PALAK",
        "name": "Organic Baby Spinach / Palak 250g",
        "slug": "spinach-palak",
        "brand": "FarmDirect",
        "price": 20.0,
        "mrp": 25.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-CORIANDER-FRESH",
        "name": "Fresh Coriander Leaves 100g",
        "slug": "coriander-fresh",
        "brand": "FarmDirect",
        "price": 12.0,
        "mrp": 15.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-MINT-PUDINA",
        "name": "Fresh Mint Leaves / Pudina 100g",
        "slug": "mint-pudina",
        "brand": "FarmDirect",
        "price": 10.0,
        "mrp": 14.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-CUCUMBER-ENGLISH",
        "name": "English Seedless Cucumbers 500g",
        "slug": "cucumber-english",
        "brand": "FarmDirect",
        "price": 30.0,
        "mrp": 36.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0707",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-GINGER-ADRAK",
        "name": "Fresh Ginger / Adrak 250g",
        "slug": "ginger-adrak",
        "brand": "FarmDirect",
        "price": 28.0,
        "mrp": 34.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-GREEN-CHILLIES",
        "name": "Fresh Green Chillies 100g",
        "slug": "green-chillies",
        "brand": "FarmDirect",
        "price": 10.0,
        "mrp": 14.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-CARROTS-OOTY",
        "name": "Ooty Fresh Carrots 500g",
        "slug": "carrots-ooty",
        "brand": "FarmDirect",
        "price": 38.0,
        "mrp": 45.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0706",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-CAULIFLOWER-FRESH",
        "name": "Fresh Cauliflower 1pc",
        "slug": "cauliflower-fresh",
        "brand": "FarmDirect",
        "price": 35.0,
        "mrp": 42.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0704",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-CABBAGE-FRESH",
        "name": "Fresh Cabbage 1pc",
        "slug": "cabbage-fresh",
        "brand": "FarmDirect",
        "price": 25.0,
        "mrp": 30.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0704",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-MUSHROOMS-BUTTON",
        "name": "Organic Button Mushrooms 200g",
        "slug": "mushrooms-button",
        "brand": "FarmDirect",
        "price": 55.0,
        "mrp": 65.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-SWEET-CORN-PACK",
        "name": "Sweet Golden Corn 2pcs",
        "slug": "sweet-corn-pack",
        "brand": "FarmDirect",
        "price": 40.0,
        "mrp": 50.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-LEMON-NIMBU-4PC",
        "name": "Fresh Lemon / Nimbu 4pcs",
        "slug": "lemon-nimbu-4pc",
        "brand": "FarmDirect",
        "price": 20.0,
        "mrp": 25.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0805",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-ORANGES-NAGPUR",
        "name": "Nagpur Sweet Oranges 1kg",
        "slug": "oranges-nagpur",
        "brand": "Himalayan Orchards",
        "price": 95.0,
        "mrp": 115.0,
        "unit": "kg",
        "is_variable_weight": True,
        "is_organic": True,
        "hsn_code": "0805",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
    {
        "sku": "PROD-MANGOES-ALPHONSO",
        "name": "Alphonso Ratnagiri Mangoes 6-Pack",
        "slug": "mangoes-alphonso",
        "brand": "Konkan Orchards",
        "price": 490.0,
        "mrp": 550.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0804",
        "shelf_life_days": 7,
        "storage": "COOL_PANTRY",
    },
]
