"""Authoritative Master Grocery Catalog - Pantry Staples & Grains."""

PANTRY_MASTER_CATALOG = [
    {
        "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG",
        "name": "Daawat Rozana Gold Basmati Rice 5kg",
        "slug": "daawat-rozana-gold-5kg",
        "brand": "Daawat",
        "base_price": 580.0,
        "sale_price": 520.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1006",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 350,
            "carbohydrates_g": 78.0,
            "protein_g": 8.5,
            "fat_g": 0.5,
            "dietary_fiber_g": 1.5,
        },
    },
    {
        "sku": "PROD-INDIA-GATE-SUPER-5KG",
        "name": "India Gate Super Premium Basmati Rice 5kg",
        "slug": "india-gate-super-5kg",
        "brand": "India Gate",
        "base_price": 820.0,
        "sale_price": 740.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1006",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 355,
            "carbohydrates_g": 78.5,
            "protein_g": 8.8,
            "fat_g": 0.6,
            "dietary_fiber_g": 1.6,
        },
    },
    {
        "sku": "PROD-FORTUNE-SHARBATI-ATTA-10KG",
        "name": "Fortune Chakki Fresh 100% Sharbati Atta 10kg",
        "slug": "fortune-sharbati-atta-10kg",
        "brand": "Fortune",
        "base_price": 460.0,
        "sale_price": 420.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1101",
        "shelf_life_days": 120,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 340,
            "carbohydrates_g": 72.0,
            "protein_g": 11.5,
            "fat_g": 1.8,
            "dietary_fiber_g": 11.0,
        },
    },
    {
        "sku": "PROD-AASHIRVAAD-SHARBATI-ATTA-5KG",
        "name": "Aashirvaad Superior MP Sharbati Atta 5kg",
        "slug": "aashirvaad-sharbati-atta-5kg",
        "brand": "Aashirvaad",
        "base_price": 295.0,
        "sale_price": 275.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1101",
        "shelf_life_days": 120,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 345,
            "carbohydrates_g": 72.5,
            "protein_g": 12.0,
            "fat_g": 1.9,
            "dietary_fiber_g": 11.5,
        },
    },
    {
        "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG",
        "name": "Tata Sampann Unpolished Toor Dal 1kg",
        "slug": "tata-sampann-toor-dal-1kg",
        "brand": "Tata Sampann",
        "base_price": 195.0,
        "sale_price": 175.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "0713",
        "shelf_life_days": 365,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 343,
            "carbohydrates_g": 62.8,
            "protein_g": 22.3,
            "fat_g": 1.5,
            "dietary_fiber_g": 15.0,
        },
    },
    {
        "sku": "PROD-TATA-SAMPANN-MOONG-DAL-1KG",
        "name": "Tata Sampann Organic Moong Dal 1kg",
        "slug": "tata-sampann-moong-dal-1kg",
        "brand": "Tata Sampann",
        "base_price": 180.0,
        "sale_price": 160.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "0713",
        "shelf_life_days": 365,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 348,
            "carbohydrates_g": 59.8,
            "protein_g": 24.0,
            "fat_g": 1.2,
            "dietary_fiber_g": 16.3,
        },
    },
    {
        "sku": "PROD-PUVI-COLD-PRESSED-GROUNDNUT-OIL-1L",
        "name": "Puvi Cold Pressed Groundnut Oil 1L",
        "slug": "puvi-cold-pressed-groundnut-oil-1l",
        "brand": "Puvi",
        "base_price": 260.0,
        "sale_price": 235.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1508",
        "shelf_life_days": 365,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 884,
            "carbohydrates_g": 0.0,
            "protein_g": 0.0,
            "fat_g": 100.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-FORTUNE-SUNFLOWER-OIL-1L",
        "name": "Fortune Sunlite Refined Sunflower Oil 1L",
        "slug": "fortune-sunflower-oil-1l",
        "brand": "Fortune",
        "base_price": 160.0,
        "sale_price": 145.0,
        "unit": "pouch",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1512",
        "shelf_life_days": 270,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 884,
            "carbohydrates_g": 0.0,
            "protein_g": 0.0,
            "fat_g": 100.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-AMUL-PURE-GHEE-1L-TIN",
        "name": "Amul Pure Ghee 1L Tin",
        "slug": "amul-pure-ghee-1l-tin",
        "brand": "Amul",
        "base_price": 640.0,
        "sale_price": 610.0,
        "unit": "tin",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "0405",
        "shelf_life_days": 270,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 900,
            "carbohydrates_g": 0.0,
            "protein_g": 0.0,
            "fat_g": 100.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-ANANDA-DESI-COW-GHEE-500ML",
        "name": "Ananda Pure Desi Cow Ghee 500ml",
        "slug": "ananda-desi-cow-ghee-500ml",
        "brand": "Ananda",
        "base_price": 460.0,
        "sale_price": 420.0,
        "unit": "jar",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "0405",
        "shelf_life_days": 270,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 900,
            "carbohydrates_g": 0.0,
            "protein_g": 0.0,
            "fat_g": 100.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-TATA-SALT-IODIZED-1KG",
        "name": "Tata Salt Vacuum Evaporated Iodized 1kg",
        "slug": "tata-salt-iodized-1kg",
        "brand": "Tata Salt",
        "base_price": 30.0,
        "sale_price": 28.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "2501",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 0,
            "carbohydrates_g": 0.0,
            "protein_g": 0.0,
            "fat_g": 0.0,
            "dietary_fiber_g": 0.0,
        },
    },
    {
        "sku": "PROD-ORGANIC-TATTVA-JAGGERY-500G",
        "name": "Organic Tattva Natural Jaggery Powder 500g",
        "slug": "organic-tattva-jaggery-500g",
        "brand": "Organic Tattva",
        "base_price": 85.0,
        "sale_price": 75.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": "Organic" in name or "Puvi" in brand,
        "is_vegetarian": True,
        "is_vegan": "Ghee" not in name,
        "is_gluten_free": "Atta" not in name,
        "hsn_code": "1701",
        "shelf_life_days": 365,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 383,
            "carbohydrates_g": 95.0,
            "protein_g": 0.4,
            "fat_g": 0.1,
            "dietary_fiber_g": 0.0,
        },
    },
]
