"""Authoritative Master Grocery Catalog - Eco-Friendly Household & Cleaners."""

HOUSEHOLD_MASTER_CATALOG = [
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-1",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #1",
        "slug": "dishwash-gel-plant-based-lime-pack-1",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-2",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #2",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-2",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-3",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #3",
        "slug": "floor-cleaner-lemongrass-1l-pack-3",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-4",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #4",
        "slug": "garbage-bags-compostable-30pc-pack-4",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-5",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #5",
        "slug": "bamboo-facial-tissues-100pulls-pack-5",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-6",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #6",
        "slug": "neem-coconut-organic-soap-125g-pack-6",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-7",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #7",
        "slug": "dishwash-gel-plant-based-lime-pack-7",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-8",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #8",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-8",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-9",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #9",
        "slug": "floor-cleaner-lemongrass-1l-pack-9",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-10",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #10",
        "slug": "garbage-bags-compostable-30pc-pack-10",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-11",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #11",
        "slug": "bamboo-facial-tissues-100pulls-pack-11",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-12",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #12",
        "slug": "neem-coconut-organic-soap-125g-pack-12",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-13",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #13",
        "slug": "dishwash-gel-plant-based-lime-pack-13",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-14",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #14",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-14",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-15",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #15",
        "slug": "floor-cleaner-lemongrass-1l-pack-15",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-16",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #16",
        "slug": "garbage-bags-compostable-30pc-pack-16",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-17",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #17",
        "slug": "bamboo-facial-tissues-100pulls-pack-17",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-18",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #18",
        "slug": "neem-coconut-organic-soap-125g-pack-18",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-19",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #19",
        "slug": "dishwash-gel-plant-based-lime-pack-19",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-20",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #20",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-20",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-21",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #21",
        "slug": "floor-cleaner-lemongrass-1l-pack-21",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-22",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #22",
        "slug": "garbage-bags-compostable-30pc-pack-22",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-23",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #23",
        "slug": "bamboo-facial-tissues-100pulls-pack-23",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-24",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #24",
        "slug": "neem-coconut-organic-soap-125g-pack-24",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-25",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #25",
        "slug": "dishwash-gel-plant-based-lime-pack-25",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-26",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #26",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-26",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-27",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #27",
        "slug": "floor-cleaner-lemongrass-1l-pack-27",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-28",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #28",
        "slug": "garbage-bags-compostable-30pc-pack-28",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-29",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #29",
        "slug": "bamboo-facial-tissues-100pulls-pack-29",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-30",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #30",
        "slug": "neem-coconut-organic-soap-125g-pack-30",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-31",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #31",
        "slug": "dishwash-gel-plant-based-lime-pack-31",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-32",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #32",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-32",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-33",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #33",
        "slug": "floor-cleaner-lemongrass-1l-pack-33",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-34",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #34",
        "slug": "garbage-bags-compostable-30pc-pack-34",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-35",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #35",
        "slug": "bamboo-facial-tissues-100pulls-pack-35",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-36",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #36",
        "slug": "neem-coconut-organic-soap-125g-pack-36",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-37",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #37",
        "slug": "dishwash-gel-plant-based-lime-pack-37",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-38",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #38",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-38",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-39",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #39",
        "slug": "floor-cleaner-lemongrass-1l-pack-39",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-40",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #40",
        "slug": "garbage-bags-compostable-30pc-pack-40",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-41",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #41",
        "slug": "bamboo-facial-tissues-100pulls-pack-41",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-42",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #42",
        "slug": "neem-coconut-organic-soap-125g-pack-42",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-43",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #43",
        "slug": "dishwash-gel-plant-based-lime-pack-43",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-44",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #44",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-44",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-45",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #45",
        "slug": "floor-cleaner-lemongrass-1l-pack-45",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-46",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #46",
        "slug": "garbage-bags-compostable-30pc-pack-46",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-47",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #47",
        "slug": "bamboo-facial-tissues-100pulls-pack-47",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-48",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #48",
        "slug": "neem-coconut-organic-soap-125g-pack-48",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-49",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #49",
        "slug": "dishwash-gel-plant-based-lime-pack-49",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-50",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #50",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-50",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-51",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #51",
        "slug": "floor-cleaner-lemongrass-1l-pack-51",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-52",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #52",
        "slug": "garbage-bags-compostable-30pc-pack-52",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-53",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #53",
        "slug": "bamboo-facial-tissues-100pulls-pack-53",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-54",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #54",
        "slug": "neem-coconut-organic-soap-125g-pack-54",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-55",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #55",
        "slug": "dishwash-gel-plant-based-lime-pack-55",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-56",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #56",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-56",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-57",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #57",
        "slug": "floor-cleaner-lemongrass-1l-pack-57",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-58",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #58",
        "slug": "garbage-bags-compostable-30pc-pack-58",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-59",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #59",
        "slug": "bamboo-facial-tissues-100pulls-pack-59",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-60",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #60",
        "slug": "neem-coconut-organic-soap-125g-pack-60",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-61",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #61",
        "slug": "dishwash-gel-plant-based-lime-pack-61",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-62",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #62",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-62",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-63",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #63",
        "slug": "floor-cleaner-lemongrass-1l-pack-63",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-64",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #64",
        "slug": "garbage-bags-compostable-30pc-pack-64",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-65",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #65",
        "slug": "bamboo-facial-tissues-100pulls-pack-65",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-66",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #66",
        "slug": "neem-coconut-organic-soap-125g-pack-66",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-67",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #67",
        "slug": "dishwash-gel-plant-based-lime-pack-67",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-68",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #68",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-68",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-69",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #69",
        "slug": "floor-cleaner-lemongrass-1l-pack-69",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-70",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #70",
        "slug": "garbage-bags-compostable-30pc-pack-70",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-71",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #71",
        "slug": "bamboo-facial-tissues-100pulls-pack-71",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-72",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #72",
        "slug": "neem-coconut-organic-soap-125g-pack-72",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-73",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #73",
        "slug": "dishwash-gel-plant-based-lime-pack-73",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-74",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #74",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-74",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-75",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #75",
        "slug": "floor-cleaner-lemongrass-1l-pack-75",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-76",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #76",
        "slug": "garbage-bags-compostable-30pc-pack-76",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-77",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #77",
        "slug": "bamboo-facial-tissues-100pulls-pack-77",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-78",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #78",
        "slug": "neem-coconut-organic-soap-125g-pack-78",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-79",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #79",
        "slug": "dishwash-gel-plant-based-lime-pack-79",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-80",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #80",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-80",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-81",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #81",
        "slug": "floor-cleaner-lemongrass-1l-pack-81",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-82",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #82",
        "slug": "garbage-bags-compostable-30pc-pack-82",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-83",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #83",
        "slug": "bamboo-facial-tissues-100pulls-pack-83",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-84",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #84",
        "slug": "neem-coconut-organic-soap-125g-pack-84",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-85",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #85",
        "slug": "dishwash-gel-plant-based-lime-pack-85",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-86",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #86",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-86",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-87",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #87",
        "slug": "floor-cleaner-lemongrass-1l-pack-87",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-88",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #88",
        "slug": "garbage-bags-compostable-30pc-pack-88",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-89",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #89",
        "slug": "bamboo-facial-tissues-100pulls-pack-89",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-90",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #90",
        "slug": "neem-coconut-organic-soap-125g-pack-90",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-91",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #91",
        "slug": "dishwash-gel-plant-based-lime-pack-91",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-92",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #92",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-92",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-93",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #93",
        "slug": "floor-cleaner-lemongrass-1l-pack-93",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-94",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #94",
        "slug": "garbage-bags-compostable-30pc-pack-94",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-95",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #95",
        "slug": "bamboo-facial-tissues-100pulls-pack-95",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-96",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #96",
        "slug": "neem-coconut-organic-soap-125g-pack-96",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-97",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #97",
        "slug": "dishwash-gel-plant-based-lime-pack-97",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-98",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #98",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-98",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-99",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #99",
        "slug": "floor-cleaner-lemongrass-1l-pack-99",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-100",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #100",
        "slug": "garbage-bags-compostable-30pc-pack-100",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-101",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #101",
        "slug": "bamboo-facial-tissues-100pulls-pack-101",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-102",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #102",
        "slug": "neem-coconut-organic-soap-125g-pack-102",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-103",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #103",
        "slug": "dishwash-gel-plant-based-lime-pack-103",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-104",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #104",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-104",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-105",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #105",
        "slug": "floor-cleaner-lemongrass-1l-pack-105",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-106",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #106",
        "slug": "garbage-bags-compostable-30pc-pack-106",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-107",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #107",
        "slug": "bamboo-facial-tissues-100pulls-pack-107",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-108",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #108",
        "slug": "neem-coconut-organic-soap-125g-pack-108",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-109",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #109",
        "slug": "dishwash-gel-plant-based-lime-pack-109",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-110",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #110",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-110",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-111",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #111",
        "slug": "floor-cleaner-lemongrass-1l-pack-111",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-112",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #112",
        "slug": "garbage-bags-compostable-30pc-pack-112",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-113",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #113",
        "slug": "bamboo-facial-tissues-100pulls-pack-113",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-114",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #114",
        "slug": "neem-coconut-organic-soap-125g-pack-114",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-115",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #115",
        "slug": "dishwash-gel-plant-based-lime-pack-115",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-116",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #116",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-116",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-117",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #117",
        "slug": "floor-cleaner-lemongrass-1l-pack-117",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-118",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #118",
        "slug": "garbage-bags-compostable-30pc-pack-118",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-119",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #119",
        "slug": "bamboo-facial-tissues-100pulls-pack-119",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-120",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #120",
        "slug": "neem-coconut-organic-soap-125g-pack-120",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-121",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #121",
        "slug": "dishwash-gel-plant-based-lime-pack-121",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-122",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #122",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-122",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-123",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #123",
        "slug": "floor-cleaner-lemongrass-1l-pack-123",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-124",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #124",
        "slug": "garbage-bags-compostable-30pc-pack-124",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-125",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #125",
        "slug": "bamboo-facial-tissues-100pulls-pack-125",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-126",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #126",
        "slug": "neem-coconut-organic-soap-125g-pack-126",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-127",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #127",
        "slug": "dishwash-gel-plant-based-lime-pack-127",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-128",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #128",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-128",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-129",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #129",
        "slug": "floor-cleaner-lemongrass-1l-pack-129",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-130",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #130",
        "slug": "garbage-bags-compostable-30pc-pack-130",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-131",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #131",
        "slug": "bamboo-facial-tissues-100pulls-pack-131",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-132",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #132",
        "slug": "neem-coconut-organic-soap-125g-pack-132",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-133",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #133",
        "slug": "dishwash-gel-plant-based-lime-pack-133",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-134",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #134",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-134",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-135",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #135",
        "slug": "floor-cleaner-lemongrass-1l-pack-135",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-136",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #136",
        "slug": "garbage-bags-compostable-30pc-pack-136",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-137",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #137",
        "slug": "bamboo-facial-tissues-100pulls-pack-137",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-138",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #138",
        "slug": "neem-coconut-organic-soap-125g-pack-138",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-139",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #139",
        "slug": "dishwash-gel-plant-based-lime-pack-139",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-140",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #140",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-140",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-141",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #141",
        "slug": "floor-cleaner-lemongrass-1l-pack-141",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-142",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #142",
        "slug": "garbage-bags-compostable-30pc-pack-142",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-143",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #143",
        "slug": "bamboo-facial-tissues-100pulls-pack-143",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-144",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #144",
        "slug": "neem-coconut-organic-soap-125g-pack-144",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-DISHWASH-GEL-PLANT-BASED-LIME-PACK-145",
        "name": "Plant-Based Natural Dishwashing Gel Lime 500ml - Pack Version #145",
        "slug": "dishwash-gel-plant-based-lime-pack-145",
        "brand": "Koparo",
        "base_price": 195.0,
        "sale_price": 165.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-LAUNDRY-DETERGENT-BIO-ENZYME-1L-PACK-146",
        "name": "Bio-Enzyme Liquid Laundry Detergent 1L - Pack Version #146",
        "slug": "laundry-detergent-bio-enzyme-1l-pack-146",
        "brand": "Koparo",
        "base_price": 399.0,
        "sale_price": 340.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-FLOOR-CLEANER-LEMONGRASS-1L-PACK-147",
        "name": "Organic Natural Floor Cleaner Lemongrass 1L - Pack Version #147",
        "slug": "floor-cleaner-lemongrass-1l-pack-147",
        "brand": "The Better Home",
        "base_price": 330.0,
        "sale_price": 280.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3402",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-GARBAGE-BAGS-COMPOSTABLE-30PC-PACK-148",
        "name": "Eco 100% Compostable Garbage Bags 30pcs Medium - Pack Version #148",
        "slug": "garbage-bags-compostable-30pc-pack-148",
        "brand": "Beco",
        "base_price": 175.0,
        "sale_price": 145.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3923",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-BAMBOO-FACIAL-TISSUES-100PULLS-PACK-149",
        "name": "Bamboo Unbleached Facial Tissues 100 Pulls 2-Ply - Pack Version #149",
        "slug": "bamboo-facial-tissues-100pulls-pack-149",
        "brand": "Beco",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "box",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "4818",
        "shelf_life_days": 1095,
        "storage_instructions": "AMBIENT",
    },
    {
        "sku": "PROD-NEEM-COCONUT-ORGANIC-SOAP-125G-PACK-150",
        "name": "Organic Cold-Pressed Neem & Coconut Soap 125g - Pack Version #150",
        "slug": "neem-coconut-organic-soap-125g-pack-150",
        "brand": "Soulflower",
        "base_price": 145.0,
        "sale_price": 120.0,
        "unit": "bar",
        "is_variable_weight": False,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "hsn_code": "3401",
        "shelf_life_days": 730,
        "storage_instructions": "AMBIENT",
    },
]
