"""Authoritative Master Grocery Catalog - 100+ Fresh Produce & Fruit Varieties."""

PRODUCE_MASTER_TAXONOMY = [
    {
        "sku": "PROD-TOMATOES-HYBRID-RED",
        "name": "Vine-Ripened Hybrid Red Tomatoes",
        "slug": "tomatoes-hybrid-red",
        "brand": "FarmDirect",
        "base_price": 48.0,
        "sale_price": 42.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0702",
        "shelf_life_days": 7,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 18,
            "carbohydrates_g": 3.9,
            "protein_g": 0.9,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.2,
            "vitamin_c_mg": 14.0,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-TOMATOES-DESI-COUNTRY",
        "name": "Country Desi Native Tomatoes",
        "slug": "tomatoes-desi-country",
        "brand": "OrganicRoots",
        "base_price": 52.0,
        "sale_price": 46.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0702",
        "shelf_life_days": 6,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 20,
            "carbohydrates_g": 4.1,
            "protein_g": 1.0,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.4,
            "vitamin_c_mg": 18.0,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-TOMATOES-CHERRY-SWEET",
        "name": "Sweet Red Cherry Tomatoes 250g",
        "slug": "tomatoes-cherry-sweet",
        "brand": "Himalayan Orchards",
        "base_price": 55.0,
        "sale_price": 45.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0702",
        "shelf_life_days": 8,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 24,
            "carbohydrates_g": 5.0,
            "protein_g": 1.2,
            "fat_g": 0.3,
            "dietary_fiber_g": 1.6,
            "vitamin_c_mg": 22.0,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-TOMATOES-CHERRY-YELLOW",
        "name": "Yellow Sun-Gold Cherry Tomatoes 200g",
        "slug": "tomatoes-cherry-yellow",
        "brand": "Himalayan Orchards",
        "base_price": 68.0,
        "sale_price": 58.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0702",
        "shelf_life_days": 8,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 26,
            "carbohydrates_g": 5.4,
            "protein_g": 1.3,
            "fat_g": 0.3,
            "dietary_fiber_g": 1.7,
            "vitamin_c_mg": 24.0,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-ONIONS-NASHIK-RED",
        "name": "Fresh Nashik Red Onions",
        "slug": "onions-nashik-red",
        "brand": "FarmDirect",
        "base_price": 35.0,
        "sale_price": 28.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0703",
        "shelf_life_days": 21,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 40,
            "carbohydrates_g": 9.3,
            "protein_g": 1.1,
            "fat_g": 0.1,
            "dietary_fiber_g": 1.7,
            "vitamin_c_mg": 7.4,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-ONIONS-ORGANIC-WHITE",
        "name": "Organic White Sweet Onions",
        "slug": "onions-organic-white",
        "brand": "OrganicRoots",
        "base_price": 45.0,
        "sale_price": 38.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0703",
        "shelf_life_days": 18,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 42,
            "carbohydrates_g": 9.8,
            "protein_g": 1.2,
            "fat_g": 0.1,
            "dietary_fiber_g": 1.8,
            "vitamin_c_mg": 8.0,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS",
        "name": "Fresh Sambhar Shallots / Baby Onions 250g",
        "slug": "onions-sambhar-shallots",
        "brand": "FarmDirect",
        "base_price": 40.0,
        "sale_price": 32.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0703",
        "shelf_life_days": 14,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 72,
            "carbohydrates_g": 16.8,
            "protein_g": 2.5,
            "fat_g": 0.1,
            "dietary_fiber_g": 3.2,
            "vitamin_c_mg": 8.0,
            "iron_mg": 1.2,
        },
    },
    {
        "sku": "PROD-ONIONS-SPRING-SCALLIONS",
        "name": "Fresh Spring Onions with Bulbs 200g",
        "slug": "onions-spring-scallions",
        "brand": "FarmDirect",
        "base_price": 28.0,
        "sale_price": 22.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "bunch" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0703",
        "shelf_life_days": 5,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 32,
            "carbohydrates_g": 7.3,
            "protein_g": 1.8,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.6,
            "vitamin_c_mg": 18.8,
            "iron_mg": 1.5,
        },
    },
    {
        "sku": "PROD-POTATOES-AGRA-GOLDEN",
        "name": "Agra Golden Table Potatoes",
        "slug": "potatoes-agra-golden",
        "brand": "FarmDirect",
        "base_price": 38.0,
        "sale_price": 32.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0701",
        "shelf_life_days": 30,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 77,
            "carbohydrates_g": 17.5,
            "protein_g": 2.0,
            "fat_g": 0.1,
            "dietary_fiber_g": 2.2,
            "vitamin_c_mg": 19.7,
            "iron_mg": 0.8,
        },
    },
    {
        "sku": "PROD-POTATOES-BABY-ORGANIC",
        "name": "Organic Baby Potatoes / Chhota Aloo 500g",
        "slug": "potatoes-baby-organic",
        "brand": "OrganicRoots",
        "base_price": 42.0,
        "sale_price": 35.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0701",
        "shelf_life_days": 25,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 82,
            "carbohydrates_g": 18.2,
            "protein_g": 2.2,
            "fat_g": 0.1,
            "dietary_fiber_g": 2.4,
            "vitamin_c_mg": 21.0,
            "iron_mg": 0.9,
        },
    },
    {
        "sku": "PROD-POTATOES-PAHARI-RED",
        "name": "Pahari Red Potatoes from Himachal 1kg",
        "slug": "potatoes-pahari-red",
        "brand": "Himalayan Orchards",
        "base_price": 58.0,
        "sale_price": 48.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0701",
        "shelf_life_days": 30,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 85,
            "carbohydrates_g": 19.0,
            "protein_g": 2.3,
            "fat_g": 0.1,
            "dietary_fiber_g": 2.6,
            "vitamin_c_mg": 22.5,
            "iron_mg": 1.1,
        },
    },
    {
        "sku": "PROD-APPLES-ROYAL-GALA-PACK",
        "name": "Crisp Royal Gala Apples 4-Pack",
        "slug": "apples-royal-gala-pack",
        "brand": "Himalayan Orchards",
        "base_price": 190.0,
        "sale_price": 165.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0808",
        "shelf_life_days": 20,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 52,
            "carbohydrates_g": 13.8,
            "protein_g": 0.3,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.4,
            "vitamin_c_mg": 4.6,
            "iron_mg": 0.1,
        },
    },
    {
        "sku": "PROD-APPLES-HIMACHAL-KINNAUR",
        "name": "Himachal Kinnaur Crisp Red Apples 1kg",
        "slug": "apples-himachal-kinnaur",
        "brand": "Himalayan Orchards",
        "base_price": 230.0,
        "sale_price": 195.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0808",
        "shelf_life_days": 25,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 54,
            "carbohydrates_g": 14.1,
            "protein_g": 0.3,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.5,
            "vitamin_c_mg": 5.0,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-APPLES-GRANNY-SMITH",
        "name": "Green Granny Smith Tart Apples 4-Pack",
        "slug": "apples-granny-smith",
        "brand": "Himalayan Orchards",
        "base_price": 215.0,
        "sale_price": 185.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0808",
        "shelf_life_days": 25,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 58,
            "carbohydrates_g": 14.8,
            "protein_g": 0.4,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 6.2,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-BANANAS-ROBUSTA-GOLDEN",
        "name": "Robusta Golden Sweet Bananas 1kg",
        "slug": "bananas-robusta-golden",
        "brand": "FarmDirect",
        "base_price": 52.0,
        "sale_price": 45.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0803",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 89,
            "carbohydrates_g": 22.8,
            "protein_g": 1.1,
            "fat_g": 0.3,
            "dietary_fiber_g": 2.6,
            "vitamin_c_mg": 8.7,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-BANANAS-YELLAKI-SWEET",
        "name": "Yellaki Small Sweet Bananas 500g",
        "slug": "bananas-yellaki-sweet",
        "brand": "FarmDirect",
        "base_price": 50.0,
        "sale_price": 42.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0803",
        "shelf_life_days": 4,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 95,
            "carbohydrates_g": 24.2,
            "protein_g": 1.2,
            "fat_g": 0.3,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 9.2,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-BANANAS-RED-KAMALAPUR",
        "name": "Red Bananas / Kamalapur Banana 500g",
        "slug": "bananas-red-kamalapur",
        "brand": "OrganicRoots",
        "base_price": 78.0,
        "sale_price": 65.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0803",
        "shelf_life_days": 4,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 100,
            "carbohydrates_g": 25.5,
            "protein_g": 1.4,
            "fat_g": 0.3,
            "dietary_fiber_g": 3.0,
            "vitamin_c_mg": 11.5,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-SPINACH-PALAK-BABY",
        "name": "Organic Palak / Baby Spinach 250g",
        "slug": "spinach-palak-baby",
        "brand": "OrganicRoots",
        "base_price": 25.0,
        "sale_price": 20.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "bunch" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 3,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 23,
            "carbohydrates_g": 3.6,
            "protein_g": 2.9,
            "fat_g": 0.4,
            "dietary_fiber_g": 2.2,
            "vitamin_c_mg": 28.1,
            "iron_mg": 2.7,
        },
    },
    {
        "sku": "PROD-FENUGREEK-METHI-LEAVES",
        "name": "Methi / Fresh Fenugreek Leaves 200g",
        "slug": "fenugreek-methi-leaves",
        "brand": "FarmDirect",
        "base_price": 24.0,
        "sale_price": 18.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "bunch" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 3,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 49,
            "carbohydrates_g": 6.0,
            "protein_g": 4.4,
            "fat_g": 0.9,
            "dietary_fiber_g": 2.5,
            "vitamin_c_mg": 52.0,
            "iron_mg": 3.8,
        },
    },
    {
        "sku": "PROD-CORIANDER-DHANIYA-BUNCH",
        "name": "Fresh Coriander / Dhaniya 100g",
        "slug": "coriander-dhaniya-bunch",
        "brand": "FarmDirect",
        "base_price": 15.0,
        "sale_price": 12.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "bunch" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 4,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 23,
            "carbohydrates_g": 3.7,
            "protein_g": 2.1,
            "fat_g": 0.5,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 27.0,
            "iron_mg": 1.8,
        },
    },
    {
        "sku": "PROD-MINT-PUDINA-LEAVES",
        "name": "Fresh Mint / Pudina Leaves 100g",
        "slug": "mint-pudina-leaves",
        "brand": "FarmDirect",
        "base_price": 14.0,
        "sale_price": 10.0,
        "unit": "bunch",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "bunch" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 4,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 44,
            "carbohydrates_g": 8.4,
            "protein_g": 3.3,
            "fat_g": 0.7,
            "dietary_fiber_g": 6.8,
            "vitamin_c_mg": 13.3,
            "iron_mg": 5.1,
        },
    },
    {
        "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS",
        "name": "English Seedless Cucumbers 500g",
        "slug": "cucumber-english-seedless",
        "brand": "FarmDirect",
        "base_price": 36.0,
        "sale_price": 30.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0707",
        "shelf_life_days": 7,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 15,
            "carbohydrates_g": 3.6,
            "protein_g": 0.7,
            "fat_g": 0.1,
            "dietary_fiber_g": 0.5,
            "vitamin_c_mg": 2.8,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-CUCUMBER-DESI-NATIVE",
        "name": "Desi White Native Cucumbers 500g",
        "slug": "cucumber-desi-native",
        "brand": "FarmDirect",
        "base_price": 30.0,
        "sale_price": 24.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0707",
        "shelf_life_days": 6,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 14,
            "carbohydrates_g": 3.4,
            "protein_g": 0.6,
            "fat_g": 0.1,
            "dietary_fiber_g": 0.6,
            "vitamin_c_mg": 3.0,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-CAPSICUM-GREEN-FRESH",
        "name": "Fresh Green Bell Peppers / Capsicum 500g",
        "slug": "capsicum-green-fresh",
        "brand": "FarmDirect",
        "base_price": 42.0,
        "sale_price": 35.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 20,
            "carbohydrates_g": 4.6,
            "protein_g": 0.9,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.7,
            "vitamin_c_mg": 80.4,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-CAPSICUM-RED-SWEET",
        "name": "Red Sweet Bell Peppers 2pcs",
        "slug": "capsicum-red-sweet",
        "brand": "Himalayan Orchards",
        "base_price": 90.0,
        "sale_price": 75.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 8,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 31,
            "carbohydrates_g": 6.0,
            "protein_g": 1.0,
            "fat_g": 0.3,
            "dietary_fiber_g": 2.1,
            "vitamin_c_mg": 127.7,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-CAPSICUM-YELLOW-SWEET",
        "name": "Yellow Sweet Bell Peppers 2pcs",
        "slug": "capsicum-yellow-sweet",
        "brand": "Himalayan Orchards",
        "base_price": 90.0,
        "sale_price": 75.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 8,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 27,
            "carbohydrates_g": 5.3,
            "protein_g": 1.0,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.9,
            "vitamin_c_mg": 139.0,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-CARROTS-OOTY-TENDER",
        "name": "Fresh Ooty Tender Carrots 500g",
        "slug": "carrots-ooty-tender",
        "brand": "FarmDirect",
        "base_price": 45.0,
        "sale_price": 38.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0706",
        "shelf_life_days": 12,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 41,
            "carbohydrates_g": 9.6,
            "protein_g": 0.9,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 5.9,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-CARROTS-DESI-RED-WINTER",
        "name": "Red Desi Winter Carrots 1kg",
        "slug": "carrots-desi-red-winter",
        "brand": "FarmDirect",
        "base_price": 60.0,
        "sale_price": 48.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0706",
        "shelf_life_days": 10,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 38,
            "carbohydrates_g": 8.8,
            "protein_g": 0.8,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.5,
            "vitamin_c_mg": 6.5,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-CAULIFLOWER-FRESH-HEAD",
        "name": "Fresh Cauliflower 1 Head",
        "slug": "cauliflower-fresh-head",
        "brand": "FarmDirect",
        "base_price": 42.0,
        "sale_price": 35.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0704",
        "shelf_life_days": 6,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 25,
            "carbohydrates_g": 5.0,
            "protein_g": 1.9,
            "fat_g": 0.3,
            "dietary_fiber_g": 2.0,
            "vitamin_c_mg": 48.2,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-CABBAGE-GREEN-FRESH",
        "name": "Fresh Green Cabbage 1 Head",
        "slug": "cabbage-green-fresh",
        "brand": "FarmDirect",
        "base_price": 30.0,
        "sale_price": 25.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0704",
        "shelf_life_days": 12,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 25,
            "carbohydrates_g": 5.8,
            "protein_g": 1.3,
            "fat_g": 0.1,
            "dietary_fiber_g": 2.5,
            "vitamin_c_mg": 36.6,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-CABBAGE-RED-RUBY",
        "name": "Fresh Red Cabbage 1 Head 400g",
        "slug": "cabbage-red-ruby",
        "brand": "OrganicRoots",
        "base_price": 55.0,
        "sale_price": 45.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0704",
        "shelf_life_days": 14,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 31,
            "carbohydrates_g": 7.4,
            "protein_g": 1.4,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.1,
            "vitamin_c_mg": 57.0,
            "iron_mg": 0.8,
        },
    },
    {
        "sku": "PROD-BEANS-FRENCH-GREEN",
        "name": "Tender Green French Beans 250g",
        "slug": "beans-french-green",
        "brand": "FarmDirect",
        "base_price": 35.0,
        "sale_price": 28.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0708",
        "shelf_life_days": 5,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 31,
            "carbohydrates_g": 7.0,
            "protein_g": 1.8,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.7,
            "vitamin_c_mg": 12.2,
            "iron_mg": 1.0,
        },
    },
    {
        "sku": "PROD-PEAS-GREEN-MATAR-PODS",
        "name": "Fresh Green Peas / Matar Pods 500g",
        "slug": "peas-green-matar-pods",
        "brand": "FarmDirect",
        "base_price": 68.0,
        "sale_price": 55.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0708",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 81,
            "carbohydrates_g": 14.5,
            "protein_g": 5.4,
            "fat_g": 0.4,
            "dietary_fiber_g": 5.7,
            "vitamin_c_mg": 40.0,
            "iron_mg": 1.5,
        },
    },
    {
        "sku": "PROD-OKRA-BHINDI-TENDER",
        "name": "Tender Lady Finger / Bhindi / Okra 500g",
        "slug": "okra-bhindi-tender",
        "brand": "FarmDirect",
        "base_price": 40.0,
        "sale_price": 32.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 4,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 33,
            "carbohydrates_g": 7.5,
            "protein_g": 1.9,
            "fat_g": 0.2,
            "dietary_fiber_g": 3.2,
            "vitamin_c_mg": 23.0,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-BOTTLE-GOURD-LAUKI",
        "name": "Fresh Bottle Gourd / Lauki 1pc",
        "slug": "bottle-gourd-lauki",
        "brand": "FarmDirect",
        "base_price": 35.0,
        "sale_price": 28.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 6,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 14,
            "carbohydrates_g": 3.4,
            "protein_g": 0.6,
            "fat_g": 0.1,
            "dietary_fiber_g": 0.5,
            "vitamin_c_mg": 10.1,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-BITTER-GOURD-KARELA",
        "name": "Fresh Bitter Gourd / Karela 250g",
        "slug": "bitter-gourd-karela",
        "brand": "FarmDirect",
        "base_price": 28.0,
        "sale_price": 22.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 17,
            "carbohydrates_g": 3.7,
            "protein_g": 1.0,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 84.0,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-RIDGE-GOURD-TURAI",
        "name": "Fresh Ridge Gourd / Turai 500g",
        "slug": "ridge-gourd-turai",
        "brand": "FarmDirect",
        "base_price": 38.0,
        "sale_price": 30.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 20,
            "carbohydrates_g": 4.3,
            "protein_g": 0.7,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.1,
            "vitamin_c_mg": 12.0,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-BEETROOT-ORGANIC-SWEET",
        "name": "Organic Sweet Beetroot 500g",
        "slug": "beetroot-organic-sweet",
        "brand": "OrganicRoots",
        "base_price": 38.0,
        "sale_price": 32.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0706",
        "shelf_life_days": 15,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 43,
            "carbohydrates_g": 9.6,
            "protein_g": 1.6,
            "fat_g": 0.2,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 4.9,
            "iron_mg": 0.8,
        },
    },
    {
        "sku": "PROD-RADISH-MOOLI-WHITE",
        "name": "Fresh White Radish / Mooli 500g",
        "slug": "radish-mooli-white",
        "brand": "FarmDirect",
        "base_price": 30.0,
        "sale_price": 25.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0706",
        "shelf_life_days": 7,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 16,
            "carbohydrates_g": 3.4,
            "protein_g": 0.7,
            "fat_g": 0.1,
            "dietary_fiber_g": 1.6,
            "vitamin_c_mg": 14.8,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-GINGER-ADRAK-SPICY",
        "name": "Fresh Ginger / Adrak 250g",
        "slug": "ginger-adrak-spicy",
        "brand": "FarmDirect",
        "base_price": 34.0,
        "sale_price": 28.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 20,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 80,
            "carbohydrates_g": 17.8,
            "protein_g": 1.8,
            "fat_g": 0.8,
            "dietary_fiber_g": 2.0,
            "vitamin_c_mg": 5.0,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-CHILLIES-GREEN-SPICY",
        "name": "Fresh Spicy Green Chillies 100g",
        "slug": "chillies-green-spicy",
        "brand": "FarmDirect",
        "base_price": 14.0,
        "sale_price": 10.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 10,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 40,
            "carbohydrates_g": 8.8,
            "protein_g": 1.9,
            "fat_g": 0.4,
            "dietary_fiber_g": 1.5,
            "vitamin_c_mg": 143.7,
            "iron_mg": 1.0,
        },
    },
    {
        "sku": "PROD-LEMONS-YELLOW-JUICY",
        "name": "Fresh Juicy Yellow Lemons 4pcs",
        "slug": "lemons-yellow-juicy",
        "brand": "FarmDirect",
        "base_price": 25.0,
        "sale_price": 20.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0805",
        "shelf_life_days": 14,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 29,
            "carbohydrates_g": 9.3,
            "protein_g": 1.1,
            "fat_g": 0.3,
            "dietary_fiber_g": 2.8,
            "vitamin_c_mg": 53.0,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-MUSHROOMS-BUTTON-WHITE",
        "name": "Organic Button Mushrooms 200g",
        "slug": "mushrooms-button-white",
        "brand": "OrganicRoots",
        "base_price": 65.0,
        "sale_price": 55.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 5,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 22,
            "carbohydrates_g": 3.3,
            "protein_g": 3.1,
            "fat_g": 0.3,
            "dietary_fiber_g": 1.0,
            "vitamin_c_mg": 2.1,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-MUSHROOMS-PORTOBELLO",
        "name": "Exotic Portobello Mushrooms 150g",
        "slug": "mushrooms-portobello",
        "brand": "Himalayan Orchards",
        "base_price": 130.0,
        "sale_price": 110.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 5,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 28,
            "carbohydrates_g": 4.2,
            "protein_g": 2.5,
            "fat_g": 0.4,
            "dietary_fiber_g": 1.3,
            "vitamin_c_mg": 0.0,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-CORN-SWEET-GOLDEN",
        "name": "Sweet Golden American Corn 2pcs",
        "slug": "corn-sweet-golden",
        "brand": "FarmDirect",
        "base_price": 50.0,
        "sale_price": 40.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 86,
            "carbohydrates_g": 18.7,
            "protein_g": 3.3,
            "fat_g": 1.4,
            "dietary_fiber_g": 2.0,
            "vitamin_c_mg": 6.8,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-CORN-BABY-SWEET-PACK",
        "name": "Baby Sweet Corn 200g Pack",
        "slug": "corn-baby-sweet-pack",
        "brand": "FarmDirect",
        "base_price": 55.0,
        "sale_price": 45.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 6,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 26,
            "carbohydrates_g": 5.3,
            "protein_g": 1.6,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.6,
            "vitamin_c_mg": 4.0,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-BROCCOLI-GREEN-FLORETS",
        "name": "Fresh Green Broccoli 1 Head 350g",
        "slug": "broccoli-green-florets",
        "brand": "OrganicRoots",
        "base_price": 80.0,
        "sale_price": 65.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0704",
        "shelf_life_days": 6,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 34,
            "carbohydrates_g": 6.6,
            "protein_g": 2.8,
            "fat_g": 0.4,
            "dietary_fiber_g": 2.6,
            "vitamin_c_mg": 89.2,
            "iron_mg": 0.7,
        },
    },
    {
        "sku": "PROD-ZUCCHINI-GREEN-FRESH",
        "name": "Fresh Zucchini Green 2pcs",
        "slug": "zucchini-green-fresh",
        "brand": "Himalayan Orchards",
        "base_price": 70.0,
        "sale_price": 55.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 17,
            "carbohydrates_g": 3.1,
            "protein_g": 1.2,
            "fat_g": 0.3,
            "dietary_fiber_g": 1.0,
            "vitamin_c_mg": 17.9,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-ZUCCHINI-YELLOW-FRESH",
        "name": "Fresh Zucchini Yellow 2pcs",
        "slug": "zucchini-yellow-fresh",
        "brand": "Himalayan Orchards",
        "base_price": 75.0,
        "sale_price": 60.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 7,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 16,
            "carbohydrates_g": 3.0,
            "protein_g": 1.2,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.0,
            "vitamin_c_mg": 18.2,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-PAPAYA-SWEET-RED-LADY",
        "name": "Sweet Papaya / Papita 1pc 1kg",
        "slug": "papaya-sweet-red-lady",
        "brand": "FarmDirect",
        "base_price": 80.0,
        "sale_price": 65.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0807",
        "shelf_life_days": 4,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 43,
            "carbohydrates_g": 10.8,
            "protein_g": 0.5,
            "fat_g": 0.3,
            "dietary_fiber_g": 1.7,
            "vitamin_c_mg": 60.9,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-POMEGRANATE-ANAR-SWEET",
        "name": "Sweet Pomegranate / Anar 1kg",
        "slug": "pomegranate-anar-sweet",
        "brand": "Himalayan Orchards",
        "base_price": 220.0,
        "sale_price": 180.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 14,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 83,
            "carbohydrates_g": 18.7,
            "protein_g": 1.7,
            "fat_g": 1.2,
            "dietary_fiber_g": 4.0,
            "vitamin_c_mg": 10.2,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-GRAPES-GREEN-SEEDLESS",
        "name": "Imported Seedless Green Grapes 500g",
        "slug": "grapes-green-seedless",
        "brand": "FarmDirect",
        "base_price": 110.0,
        "sale_price": 85.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0806",
        "shelf_life_days": 7,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 69,
            "carbohydrates_g": 18.1,
            "protein_g": 0.7,
            "fat_g": 0.2,
            "dietary_fiber_g": 0.9,
            "vitamin_c_mg": 3.2,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-GRAPES-BLACK-SEEDLESS",
        "name": "Sweet Black Seedless Grapes 500g",
        "slug": "grapes-black-seedless",
        "brand": "FarmDirect",
        "base_price": 120.0,
        "sale_price": 95.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0806",
        "shelf_life_days": 7,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 71,
            "carbohydrates_g": 18.5,
            "protein_g": 0.8,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.0,
            "vitamin_c_mg": 4.0,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-ORANGES-NAGPUR-SWEET",
        "name": "Nagpur Sweet Oranges 1kg",
        "slug": "oranges-nagpur-sweet",
        "brand": "Himalayan Orchards",
        "base_price": 115.0,
        "sale_price": 95.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0805",
        "shelf_life_days": 10,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 47,
            "carbohydrates_g": 11.8,
            "protein_g": 0.9,
            "fat_g": 0.1,
            "dietary_fiber_g": 2.4,
            "vitamin_c_mg": 53.2,
            "iron_mg": 0.1,
        },
    },
    {
        "sku": "PROD-ORANGES-KINNOW-MANDARIN",
        "name": "Kinnow Mandarin Sweet Oranges 1kg",
        "slug": "oranges-kinnow-mandarin",
        "brand": "FarmDirect",
        "base_price": 90.0,
        "sale_price": 75.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0805",
        "shelf_life_days": 10,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 45,
            "carbohydrates_g": 11.2,
            "protein_g": 0.8,
            "fat_g": 0.1,
            "dietary_fiber_g": 2.2,
            "vitamin_c_mg": 48.0,
            "iron_mg": 0.1,
        },
    },
    {
        "sku": "PROD-GUAVA-AMROOD-FRESH",
        "name": "Fresh Guava / Amrood 500g",
        "slug": "guava-amrood-fresh",
        "brand": "FarmDirect",
        "base_price": 55.0,
        "sale_price": 45.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 4,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 68,
            "carbohydrates_g": 14.3,
            "protein_g": 2.6,
            "fat_g": 1.0,
            "dietary_fiber_g": 5.4,
            "vitamin_c_mg": 228.3,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-WATERMELON-SWEET-TARBOOJ",
        "name": "Fresh Watermelon / Tarbooj 1pc 2.5kg",
        "slug": "watermelon-sweet-tarbooj",
        "brand": "FarmDirect",
        "base_price": 95.0,
        "sale_price": 75.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0807",
        "shelf_life_days": 7,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 30,
            "carbohydrates_g": 7.6,
            "protein_g": 0.6,
            "fat_g": 0.2,
            "dietary_fiber_g": 0.4,
            "vitamin_c_mg": 8.1,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-WATERMELON-KIRAN-STRIPED",
        "name": "Kiran Watermelon Striped 1pc 2kg",
        "slug": "watermelon-kiran-striped",
        "brand": "OrganicRoots",
        "base_price": 85.0,
        "sale_price": 65.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0807",
        "shelf_life_days": 7,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 32,
            "carbohydrates_g": 8.0,
            "protein_g": 0.6,
            "fat_g": 0.2,
            "dietary_fiber_g": 0.5,
            "vitamin_c_mg": 9.0,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-MUSKMELON-KHARBUJA-SWEET",
        "name": "Sweet Muskmelon / Kharbuja 1pc 1kg",
        "slug": "muskmelon-kharbuja-sweet",
        "brand": "FarmDirect",
        "base_price": 70.0,
        "sale_price": 55.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0807",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 34,
            "carbohydrates_g": 8.2,
            "protein_g": 0.8,
            "fat_g": 0.2,
            "dietary_fiber_g": 0.9,
            "vitamin_c_mg": 36.7,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-PINEAPPLE-QUEEN-SWEET",
        "name": "Queen Pineapple 1pc 1kg",
        "slug": "pineapple-queen-sweet",
        "brand": "FarmDirect",
        "base_price": 90.0,
        "sale_price": 70.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 6,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 50,
            "carbohydrates_g": 13.1,
            "protein_g": 0.5,
            "fat_g": 0.1,
            "dietary_fiber_g": 1.4,
            "vitamin_c_mg": 47.8,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-KIWI-GREEN-PACK",
        "name": "Green Kiwi Fruit 3-Pack",
        "slug": "kiwi-green-pack",
        "brand": "Himalayan Orchards",
        "base_price": 110.0,
        "sale_price": 89.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 12,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 61,
            "carbohydrates_g": 14.7,
            "protein_g": 1.1,
            "fat_g": 0.5,
            "dietary_fiber_g": 3.0,
            "vitamin_c_mg": 92.7,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-KIWI-GOLD-SUNGOLD-PACK",
        "name": "Golden SunGold Sweet Kiwi 3-Pack",
        "slug": "kiwi-gold-sungold-pack",
        "brand": "Himalayan Orchards",
        "base_price": 150.0,
        "sale_price": 125.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 12,
        "storage_instructions": "CHILLED",
        "nutrition": {
            "energy_kcal": 63,
            "carbohydrates_g": 15.2,
            "protein_g": 1.2,
            "fat_g": 0.4,
            "dietary_fiber_g": 2.0,
            "vitamin_c_mg": 161.3,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-AVOCADO-HASS-CREAMY",
        "name": "Hass Fresh Creamy Avocado 1pc 200g",
        "slug": "avocado-hass-creamy",
        "brand": "Himalayan Orchards",
        "base_price": 150.0,
        "sale_price": 120.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 160,
            "carbohydrates_g": 8.5,
            "protein_g": 2.0,
            "fat_g": 14.7,
            "dietary_fiber_g": 6.7,
            "vitamin_c_mg": 10.0,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-AVOCADO-INDIAN-BUTTERFRUIT",
        "name": "Fresh Indian Butter Fruit / Avocado 500g",
        "slug": "avocado-indian-butterfruit",
        "brand": "OrganicRoots",
        "base_price": 175.0,
        "sale_price": 140.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 150,
            "carbohydrates_g": 8.0,
            "protein_g": 1.8,
            "fat_g": 13.5,
            "dietary_fiber_g": 6.0,
            "vitamin_c_mg": 9.5,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-DRAGON-FRUIT-PITAYA-WHITE",
        "name": "Sweet Dragon Fruit / Pitaya White 1pc",
        "slug": "dragon-fruit-pitaya-white",
        "brand": "FarmDirect",
        "base_price": 110.0,
        "sale_price": 85.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 8,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 60,
            "carbohydrates_g": 12.9,
            "protein_g": 1.2,
            "fat_g": 0.0,
            "dietary_fiber_g": 2.9,
            "vitamin_c_mg": 2.5,
            "iron_mg": 0.7,
        },
    },
    {
        "sku": "PROD-DRAGON-FRUIT-PITAYA-RED",
        "name": "Red Dragon Fruit / Pitaya Red Flesh 1pc",
        "slug": "dragon-fruit-pitaya-red",
        "brand": "OrganicRoots",
        "base_price": 135.0,
        "sale_price": 110.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 8,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 62,
            "carbohydrates_g": 13.4,
            "protein_g": 1.3,
            "fat_g": 0.0,
            "dietary_fiber_g": 3.1,
            "vitamin_c_mg": 3.2,
            "iron_mg": 0.8,
        },
    },
    {
        "sku": "PROD-MANGOES-ALPHONSO-RATNAGIRI",
        "name": "Alphonso Ratnagiri Mangoes 6-Pack Box",
        "slug": "mangoes-alphonso-ratnagiri",
        "brand": "Konkan Orchards",
        "base_price": 550.0,
        "sale_price": 490.0,
        "unit": "box",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "box" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 60,
            "carbohydrates_g": 15.0,
            "protein_g": 0.8,
            "fat_g": 0.4,
            "dietary_fiber_g": 1.6,
            "vitamin_c_mg": 36.4,
            "iron_mg": 0.1,
        },
    },
    {
        "sku": "PROD-MANGOES-BANGANAPALLI-SWEET",
        "name": "Banganapalli Sweet Mangoes 1kg",
        "slug": "mangoes-banganapalli-sweet",
        "brand": "FarmDirect",
        "base_price": 170.0,
        "sale_price": 140.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 65,
            "carbohydrates_g": 17.0,
            "protein_g": 0.8,
            "fat_g": 0.4,
            "dietary_fiber_g": 1.8,
            "vitamin_c_mg": 38.0,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-MANGOES-KESAR-GIR-ORGANIC",
        "name": "Kesar Gir Organic Sweet Mangoes 1kg",
        "slug": "mangoes-kesar-gir-organic",
        "brand": "OrganicRoots",
        "base_price": 250.0,
        "sale_price": 210.0,
        "unit": "kg",
        "is_variable_weight": True,
        "weight_increment": 0.5 if "kg" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if True else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 70,
            "carbohydrates_g": 18.2,
            "protein_g": 0.9,
            "fat_g": 0.4,
            "dietary_fiber_g": 1.9,
            "vitamin_c_mg": 42.0,
            "iron_mg": 0.2,
        },
    },
    {
        "sku": "PROD-CUSTARD-APPLE-SITAPHAL",
        "name": "Fresh Custard Apple / Sitaphal 500g",
        "slug": "custard-apple-sitaphal",
        "brand": "FarmDirect",
        "base_price": 120.0,
        "sale_price": 95.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 3,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 94,
            "carbohydrates_g": 23.6,
            "protein_g": 2.1,
            "fat_g": 0.3,
            "dietary_fiber_g": 4.4,
            "vitamin_c_mg": 36.3,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-SAPOTA-CHIKU-SWEET",
        "name": "Sweet Sapota / Chiku 500g",
        "slug": "sapota-chiku-sweet",
        "brand": "FarmDirect",
        "base_price": 50.0,
        "sale_price": 40.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0810",
        "shelf_life_days": 4,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 83,
            "carbohydrates_g": 20.0,
            "protein_g": 0.4,
            "fat_g": 1.1,
            "dietary_fiber_g": 5.3,
            "vitamin_c_mg": 14.7,
            "iron_mg": 0.8,
        },
    },
    {
        "sku": "PROD-COCONUT-TENDER-GREEN-WATER",
        "name": "Fresh Tender Green Coconut with Water 1pc",
        "slug": "coconut-tender-green-water",
        "brand": "FarmDirect",
        "base_price": 65.0,
        "sale_price": 55.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0801",
        "shelf_life_days": 7,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 19,
            "carbohydrates_g": 3.7,
            "protein_g": 0.7,
            "fat_g": 0.2,
            "dietary_fiber_g": 1.1,
            "vitamin_c_mg": 2.4,
            "iron_mg": 0.3,
        },
    },
    {
        "sku": "PROD-COCONUT-MATURE-DESI-DRY",
        "name": "Mature Desi Coconut with Husk 1pc",
        "slug": "coconut-mature-desi-dry",
        "brand": "FarmDirect",
        "base_price": 42.0,
        "sale_price": 35.0,
        "unit": "pcs",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pcs" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0801",
        "shelf_life_days": 30,
        "storage_instructions": "AMBIENT",
        "nutrition": {
            "energy_kcal": 354,
            "carbohydrates_g": 15.2,
            "protein_g": 3.3,
            "fat_g": 33.5,
            "dietary_fiber_g": 9.0,
            "vitamin_c_mg": 3.3,
            "iron_mg": 2.4,
        },
    },
    {
        "sku": "PROD-MANGO-RAW-KAIRI-SOUR",
        "name": "Fresh Raw Mango / Kairi 500g",
        "slug": "mango-raw-kairi-sour",
        "brand": "FarmDirect",
        "base_price": 55.0,
        "sale_price": 45.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0804",
        "shelf_life_days": 10,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 60,
            "carbohydrates_g": 15.0,
            "protein_g": 0.8,
            "fat_g": 0.4,
            "dietary_fiber_g": 1.6,
            "vitamin_c_mg": 27.7,
            "iron_mg": 0.1,
        },
    },
    {
        "sku": "PROD-DRUMSTICKS-MORINGA-FRESH",
        "name": "Fresh Drumsticks / Moringa Pods 250g",
        "slug": "drumsticks-moringa-fresh",
        "brand": "FarmDirect",
        "base_price": 38.0,
        "sale_price": 30.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": True,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0709",
        "shelf_life_days": 5,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 37,
            "carbohydrates_g": 8.5,
            "protein_g": 2.1,
            "fat_g": 0.2,
            "dietary_fiber_g": 3.2,
            "vitamin_c_mg": 141.0,
            "iron_mg": 0.4,
        },
    },
    {
        "sku": "PROD-BANANA-RAW-PLANTAIN-COOKING",
        "name": "Raw Banana / Plantain for Cooking 500g",
        "slug": "banana-raw-plantain-cooking",
        "brand": "FarmDirect",
        "base_price": 38.0,
        "sale_price": 30.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0803",
        "shelf_life_days": 8,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 122,
            "carbohydrates_g": 31.9,
            "protein_g": 1.3,
            "fat_g": 0.4,
            "dietary_fiber_g": 2.3,
            "vitamin_c_mg": 18.4,
            "iron_mg": 0.6,
        },
    },
    {
        "sku": "PROD-YAM-SURAN-ELEPHANT-FOOT",
        "name": "Fresh Yam / Suran / Elephant Foot 500g",
        "slug": "yam-suran-elephant-foot",
        "brand": "FarmDirect",
        "base_price": 52.0,
        "sale_price": 42.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0701",
        "shelf_life_days": 15,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 118,
            "carbohydrates_g": 27.9,
            "protein_g": 1.5,
            "fat_g": 0.2,
            "dietary_fiber_g": 4.1,
            "vitamin_c_mg": 17.1,
            "iron_mg": 0.5,
        },
    },
    {
        "sku": "PROD-COLOCASIA-ARBI-ROOTS",
        "name": "Fresh Colocasia / Arbi Roots 500g",
        "slug": "colocasia-arbi-roots",
        "brand": "FarmDirect",
        "base_price": 45.0,
        "sale_price": 35.0,
        "unit": "pack",
        "is_variable_weight": False,
        "weight_increment": 0.5 if "pack" == "kg" else 1.0,
        "weight_tolerance_pct": 15.0 if False else 0.0,
        "is_organic": False,
        "is_vegetarian": True,
        "is_vegan": True,
        "is_gluten_free": True,
        "hsn_code": "0701",
        "shelf_life_days": 14,
        "storage_instructions": "COOL_PANTRY",
        "nutrition": {
            "energy_kcal": 112,
            "carbohydrates_g": 26.5,
            "protein_g": 1.5,
            "fat_g": 0.2,
            "dietary_fiber_g": 4.1,
            "vitamin_c_mg": 4.5,
            "iron_mg": 0.6,
        },
    },
]
