"""Authoritative Master Grocery Catalog - Pantry Staples & Cooking Oils."""

PANTRY_CATALOG = [
    {
        "sku": "PROD-DAAWAT-BASMATI-RICE-5KG",
        "name": "Daawat Rozana Gold Basmati Rice 5kg",
        "slug": "daawat-basmati-rice-5kg",
        "brand": "Daawat",
        "price": 520.0,
        "mrp": 580.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1006",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-INDIA-GATE-SUPER-BASMATI-5KG",
        "name": "India Gate Super Premium Basmati Rice 5kg",
        "slug": "india-gate-super-basmati-5kg",
        "brand": "India Gate",
        "price": 740.0,
        "mrp": 820.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1006",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-FORTUNE-SHARBATI-ATTA-10KG",
        "name": "Fortune Chakki Fresh 100% Sharbati Atta 10kg",
        "slug": "fortune-sharbati-atta-10kg",
        "brand": "Fortune",
        "price": 420.0,
        "mrp": 460.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1101",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-AASHIRVAAD-SHARBATI-ATTA-5KG",
        "name": "Aashirvaad Superior MP Sharbati Atta 5kg",
        "slug": "aashirvaad-sharbati-atta-5kg",
        "brand": "Aashirvaad",
        "price": 275.0,
        "mrp": 295.0,
        "unit": "bag",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1101",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG",
        "name": "Tata Sampann Unpolished Toor Dal 1kg",
        "slug": "tata-sampann-toor-dal-1kg",
        "brand": "Tata Sampann",
        "price": 175.0,
        "mrp": 195.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0713",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-TATA-SAMPANN-MOONG-DAL-1KG",
        "name": "Tata Sampann Organic Moong Dal 1kg",
        "slug": "tata-sampann-moong-dal-1kg",
        "brand": "Tata Sampann",
        "price": 160.0,
        "mrp": 180.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0713",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-TATA-SAMPANN-CHANA-DAL-1KG",
        "name": "Tata Sampann Unpolished Chana Dal 1kg",
        "slug": "tata-sampann-chana-dal-1kg",
        "brand": "Tata Sampann",
        "price": 110.0,
        "mrp": 125.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0713",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-PUVI-COLD-PRESSED-GROUNDNUT-OIL-1L",
        "name": "Puvi Cold Pressed Groundnut Oil 1L",
        "slug": "puvi-cold-pressed-groundnut-oil-1l",
        "brand": "Puvi",
        "price": 235.0,
        "mrp": 260.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "1508",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-FORTUNE-SUNFLOWER-OIL-1L",
        "name": "Fortune Sunlite Refined Sunflower Oil 1L",
        "slug": "fortune-sunflower-oil-1l",
        "brand": "Fortune",
        "price": 145.0,
        "mrp": 160.0,
        "unit": "pouch",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1512",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-FORTUNE-MUSTARD-OIL-1L",
        "name": "Fortune Kachi Ghani Pure Mustard Oil 1L",
        "slug": "fortune-mustard-oil-1l",
        "brand": "Fortune",
        "price": 160.0,
        "mrp": 175.0,
        "unit": "bottle",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1514",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-AMUL-PURE-GHEE-1L-TIN",
        "name": "Amul Pure Ghee 1L Tin",
        "slug": "amul-pure-ghee-1l-tin",
        "brand": "Amul",
        "price": 610.0,
        "mrp": 640.0,
        "unit": "tin",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "0405",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-ANANDA-DESI-COW-GHEE-500ML",
        "name": "Ananda Pure Desi Cow Ghee 500ml",
        "slug": "ananda-desi-cow-ghee-500ml",
        "brand": "Ananda",
        "price": 420.0,
        "mrp": 460.0,
        "unit": "jar",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "0405",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-TATA-SALT-IODIZED-1KG",
        "name": "Tata Salt Vacuum Evaporated Iodized 1kg",
        "slug": "tata-salt-iodized-1kg",
        "brand": "Tata Salt",
        "price": 28.0,
        "mrp": 30.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "2501",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-TATA-SALT-LITE-1KG",
        "name": "Tata Salt Lite Low Sodium 1kg",
        "slug": "tata-salt-lite-1kg",
        "brand": "Tata Salt",
        "price": 42.0,
        "mrp": 48.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "2501",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-MADHUR-REFINED-SUGAR-1KG",
        "name": "Madhur Pure & Hygienic Refined Sugar 1kg",
        "slug": "madhur-refined-sugar-1kg",
        "brand": "Madhur",
        "price": 56.0,
        "mrp": 62.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": False,
        "hsn_code": "1701",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
    {
        "sku": "PROD-ORGANIC-TATTVA-JAGGERY-POWDER-500G",
        "name": "Organic Tattva Natural Jaggery Powder 500g",
        "slug": "organic-tattva-jaggery-powder-500g",
        "brand": "Organic Tattva",
        "price": 75.0,
        "mrp": 85.0,
        "unit": "pack",
        "is_variable_weight": False,
        "is_organic": True,
        "hsn_code": "1701",
        "shelf_life_days": 365,
        "storage": "AMBIENT",
    },
]
