"""Authoritative Recipe Knowledge Base and Measured SKU Bundler."""
from typing import List, Dict, Any
from pydantic import BaseModel

class RecipeIngredient(BaseModel):
    name: str
    sku: str
    quantity: float
    unit: str
    price: float

class MasterRecipe(BaseModel):
    id: str
    title: str
    slug: str
    cuisine: str
    category: str
    prep_time_mins: int
    cook_time_mins: int
    servings: int
    calories: int
    difficulty: str
    ingredients: List[RecipeIngredient]
    instructions: List[str]

MASTER_RECIPE_DATABASE: List[Dict[str, Any]] = [
    {
        "id": "rec-1",
        "title": "Paneer Butter Masala - Chef Style Variation #1",
        "slug": "recipe-paneer-butter-masala-var-1",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-2",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #2",
        "slug": "recipe-hyderabadi-dum-biryani-var-2",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-3",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #3",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-3",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-4",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #4",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-4",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-5",
        "title": "Spicy Misal Pav - Chef Style Variation #5",
        "slug": "recipe-spicy-misal-pav-var-5",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-6",
        "title": "Paneer Butter Masala - Chef Style Variation #6",
        "slug": "recipe-paneer-butter-masala-var-6",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-7",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #7",
        "slug": "recipe-hyderabadi-dum-biryani-var-7",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-8",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #8",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-8",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-9",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #9",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-9",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-10",
        "title": "Spicy Misal Pav - Chef Style Variation #10",
        "slug": "recipe-spicy-misal-pav-var-10",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-11",
        "title": "Paneer Butter Masala - Chef Style Variation #11",
        "slug": "recipe-paneer-butter-masala-var-11",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-12",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #12",
        "slug": "recipe-hyderabadi-dum-biryani-var-12",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-13",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #13",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-13",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-14",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #14",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-14",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-15",
        "title": "Spicy Misal Pav - Chef Style Variation #15",
        "slug": "recipe-spicy-misal-pav-var-15",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-16",
        "title": "Paneer Butter Masala - Chef Style Variation #16",
        "slug": "recipe-paneer-butter-masala-var-16",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-17",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #17",
        "slug": "recipe-hyderabadi-dum-biryani-var-17",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-18",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #18",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-18",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-19",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #19",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-19",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-20",
        "title": "Spicy Misal Pav - Chef Style Variation #20",
        "slug": "recipe-spicy-misal-pav-var-20",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-21",
        "title": "Paneer Butter Masala - Chef Style Variation #21",
        "slug": "recipe-paneer-butter-masala-var-21",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-22",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #22",
        "slug": "recipe-hyderabadi-dum-biryani-var-22",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-23",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #23",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-23",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-24",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #24",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-24",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-25",
        "title": "Spicy Misal Pav - Chef Style Variation #25",
        "slug": "recipe-spicy-misal-pav-var-25",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-26",
        "title": "Paneer Butter Masala - Chef Style Variation #26",
        "slug": "recipe-paneer-butter-masala-var-26",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-27",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #27",
        "slug": "recipe-hyderabadi-dum-biryani-var-27",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-28",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #28",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-28",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-29",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #29",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-29",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-30",
        "title": "Spicy Misal Pav - Chef Style Variation #30",
        "slug": "recipe-spicy-misal-pav-var-30",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-31",
        "title": "Paneer Butter Masala - Chef Style Variation #31",
        "slug": "recipe-paneer-butter-masala-var-31",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-32",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #32",
        "slug": "recipe-hyderabadi-dum-biryani-var-32",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-33",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #33",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-33",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-34",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #34",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-34",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-35",
        "title": "Spicy Misal Pav - Chef Style Variation #35",
        "slug": "recipe-spicy-misal-pav-var-35",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-36",
        "title": "Paneer Butter Masala - Chef Style Variation #36",
        "slug": "recipe-paneer-butter-masala-var-36",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-37",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #37",
        "slug": "recipe-hyderabadi-dum-biryani-var-37",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-38",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #38",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-38",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-39",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #39",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-39",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-40",
        "title": "Spicy Misal Pav - Chef Style Variation #40",
        "slug": "recipe-spicy-misal-pav-var-40",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-41",
        "title": "Paneer Butter Masala - Chef Style Variation #41",
        "slug": "recipe-paneer-butter-masala-var-41",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-42",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #42",
        "slug": "recipe-hyderabadi-dum-biryani-var-42",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-43",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #43",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-43",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-44",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #44",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-44",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-45",
        "title": "Spicy Misal Pav - Chef Style Variation #45",
        "slug": "recipe-spicy-misal-pav-var-45",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-46",
        "title": "Paneer Butter Masala - Chef Style Variation #46",
        "slug": "recipe-paneer-butter-masala-var-46",
        "cuisine": "North Indian",
        "category": "Curry",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 380,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Fresh Malai Paneer 200g", "sku": "PROD-AMUL-FRESH-MALAI-PANEER-200G", "quantity": 1.0, "unit": "pack", "price": 92.0},
            {"name": "Vine-Ripened Hybrid Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.5, "unit": "kg", "price": 21.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "Fresh Ginger & Garlic 100g", "sku": "PROD-GINGER-ADRAK-SPICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-47",
        "title": "Hyderabadi Dum Biryani - Chef Style Variation #47",
        "slug": "recipe-hyderabadi-dum-biryani-var-47",
        "cuisine": "South Indian",
        "category": "Rice",
        "prep_time_mins": 30,
        "cook_time_mins": 45,
        "servings": 6,
        "calories": 520,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Daawat Rozana Gold Basmati Rice 5kg", "sku": "PROD-DAAWAT-ROZANA-GOLD-5KG", "quantity": 1.0, "unit": "kg", "price": 104.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 1.0, "unit": "kg", "price": 28.0},
            {"name": "Mother Dairy Classic Dahi 400g", "sku": "PROD-MOTHER-DAIRY-CLASSIC-DAHI-400G", "quantity": 1.0, "unit": "tub", "price": 40.0},
            {"name": "Fresh Mint & Coriander", "sku": "PROD-MINT-PUDINA-LEAVES", "quantity": 1.0, "unit": "bunch", "price": 22.0},
            {"name": "Amul Pure Ghee", "sku": "PROD-AMUL-PURE-GHEE-1L-TIN", "quantity": 0.1, "unit": "tin", "price": 61.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-48",
        "title": "Authentic Sambar & Soft Idli - Chef Style Variation #48",
        "slug": "recipe-authentic-sambar-&-soft-idli-var-48",
        "cuisine": "South Indian",
        "category": "Breakfast",
        "prep_time_mins": 15,
        "cook_time_mins": 20,
        "servings": 4,
        "calories": 260,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Tata Sampann Toor Dal 1kg", "sku": "PROD-TATA-SAMPANN-TOOR-DAL-1KG", "quantity": 0.25, "unit": "kg", "price": 44.0},
            {"name": "Shallots / Sambhar Onions", "sku": "PROD-ONIONS-SAMBHAR-SHALLOTS", "quantity": 1.0, "unit": "pack", "price": 32.0},
            {"name": "Fresh Drumsticks / Moringa", "sku": "PROD-DRUMSTICKS-MORINGA-FRESH", "quantity": 1.0, "unit": "pack", "price": 30.0},
            {"name": "Fresh Tomatoes", "sku": "PROD-TOMATOES-HYBRID-RED", "quantity": 0.25, "unit": "kg", "price": 10.5},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-49",
        "title": "Creamy Garlic Mushroom Pasta - Chef Style Variation #49",
        "slug": "recipe-creamy-garlic-mushroom-pasta-var-49",
        "cuisine": "Continental",
        "category": "Pasta",
        "prep_time_mins": 10,
        "cook_time_mins": 15,
        "servings": 2,
        "calories": 410,
        "difficulty": "Easy",
        "ingredients": [
            {"name": "Organic Button Mushrooms 200g", "sku": "PROD-MUSHROOMS-BUTTON-WHITE", "quantity": 1.0, "unit": "pack", "price": 55.0},
            {"name": "Amul Pasteurised Butter 100g", "sku": "PROD-AMUL-BUTTER-100G", "quantity": 1.0, "unit": "pack", "price": 58.0},
            {"name": "English Seedless Cucumbers", "sku": "PROD-CUCUMBER-ENGLISH-SEEDLESS", "quantity": 0.5, "unit": "kg", "price": 30.0},
            {"name": "Fresh Cream 200ml", "sku": "PROD-AMUL-FRESH-CREAM-200ML", "quantity": 1.0, "unit": "pack", "price": 65.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
    {
        "id": "rec-50",
        "title": "Spicy Misal Pav - Chef Style Variation #50",
        "slug": "recipe-spicy-misal-pav-var-50",
        "cuisine": "Maharashtrian",
        "category": "Snack",
        "prep_time_mins": 20,
        "cook_time_mins": 25,
        "servings": 4,
        "calories": 340,
        "difficulty": "Medium",
        "ingredients": [
            {"name": "Organic Sprouts Mix 250g", "sku": "PROD-SPROUTS-MIX-ORGANIC-250G", "quantity": 1.0, "unit": "pack", "price": 45.0},
            {"name": "Fresh Nashik Red Onions", "sku": "PROD-ONIONS-NASHIK-RED", "quantity": 0.5, "unit": "kg", "price": 14.0},
            {"name": "Fresh Lemon 4pcs", "sku": "PROD-LEMONS-YELLOW-JUICY", "quantity": 1.0, "unit": "pack", "price": 20.0},
            {"name": "Fresh Pav Buns 6-Pack", "sku": "PROD-FRESH-PAV-BUNS-6PC", "quantity": 1.0, "unit": "pack", "price": 35.0},
        ],
        "instructions": [
            "Wash and prep all fresh organic ingredients thoroughly.",
            "Heat cooking pan with fresh butter or cold-pressed oil.",
            "Saute aromatics including onions, ginger, and garlic until golden brown.",
            "Add primary produce and simmer gently under medium heat.",
            "Garnish with fresh coriander and serve hot with accompaniments.",
        ],
    },
]
